In [68]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets

In [69]:
iris=datasets.load_iris()

In [70]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [71]:
df=pd.DataFrame(iris.data,columns=iris.feature_names)

In [72]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [73]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.3,random_state=0)

In [74]:
from sklearn import svm
svc=svm.SVC(C=30,gamma='auto',kernel='rbf')
svc.fit(X_train,y_train)
svc.score(X_test,y_test)

0.9777777777777777

In [75]:
from sklearn.model_selection import cross_val_score

In [76]:
cross_val_score(svm.SVC(C=30,gamma='auto',kernel='rbf'),X_test,y_test,cv=5)

array([1.        , 0.88888889, 1.        , 1.        , 0.88888889])

In [77]:
cross_val_score(svm.SVC(C=30,gamma='auto',kernel='linear'),X_test,y_test,cv=5)

array([1.        , 0.88888889, 0.88888889, 1.        , 0.88888889])

In [78]:
cross_val_score(svm.SVC(C=10,gamma='auto',kernel='linear'),X_test,y_test,cv=5)

array([1.        , 0.88888889, 1.        , 1.        , 0.88888889])

In [79]:
kernel=['rbf','linear']
C=[1,10,30]
avr_score={}

for kar in kernel:
    for c in C:
        cross_score=cross_val_score(svm.SVC(C=c,kernel=kar,gamma='auto'),X_test,y_test,cv=5)
        avr_score[kar +'_' + str(c)]=np.average(cross_score)

avr_score
  

{'rbf_1': 0.888888888888889,
 'rbf_10': 0.9555555555555555,
 'rbf_30': 0.9555555555555555,
 'linear_1': 0.9333333333333332,
 'linear_10': 0.9555555555555555,
 'linear_30': 0.9333333333333332}

In [80]:
from sklearn.model_selection import GridSearchCV
grid_search_cv=GridSearchCV(svm.SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False)

In [81]:
grid_search_cv.fit(X_train,y_train)
dir(grid_search_cv)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_is_fitted',
 '_check_n_features',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'iid',
 'inverse_transform',
 'multimetric_',
 'n_features_in_',
 'n_jobs',
 'n_splits_',
 'param_grid',
 'pre_

In [82]:
grid_search_cv.cv_results_

{'mean_fit_time': array([0.00199504, 0.00079823, 0.00079193, 0.00059743, 0.00079494,
        0.00059881]),
 'std_fit_time': array([0.00063113, 0.00039911, 0.00039633, 0.0004878 , 0.0003975 ,
        0.00048893]),
 'mean_score_time': array([0.00099778, 0.00019937, 0.        , 0.00019999, 0.        ,
        0.00019932]),
 'std_score_time': array([0.00089239, 0.00039873, 0.        , 0.00039997, 0.        ,
        0.00039864]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],


In [83]:
df=pd.DataFrame(grid_search_cv.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001995      0.000631         0.000998        0.000892       1   
1       0.000798      0.000399         0.000199        0.000399       1   
2       0.000792      0.000396         0.000000        0.000000      10   
3       0.000597      0.000488         0.000200        0.000400      10   
4       0.000795      0.000398         0.000000        0.000000      20   
5       0.000599      0.000489         0.000199        0.000399      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           1.000000   
1       linear   {'C': 1, 'kernel': 'linear'}           0.952381   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.952381   
3       linear  {'C': 10, 'kernel': 'linear'}           0.904762   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.904762   
5       linear  {'C': 20, 'kernel': 'linear'}           0.809524   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0                1.0           0.904762           0.952381   
1                1.0                1.0           0.952381           0.952381   
2                1.0                1.0           0.904762           0.952381   
3                1.0                1.0           0.904762           0.952381   
4                1.0                1.0           0.904762           0.952381   
5                1.0                1.0           0.904762           0.952381   

   mean_test_score  std_test_score  rank_test_score  
0         0.971429        0.038095                2  
1         0.971429        0.023328                1  
2         0.961905        0.035635                3  
3         0.952381        0.042592                4  
4         0.952381        0.042592                4  
5         0.933333        0.071270                6

In [84]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.971429
1       1       linear         0.971429
2      10          rbf         0.961905
3      10       linear         0.952381
4      20          rbf         0.952381
5      20       linear         0.933333

In [85]:
grid_search_cv.best_score_

0.9714285714285715

In [86]:
grid_search_cv.best_params_

{'C': 1, 'kernel': 'linear'}

In [87]:
from sklearn.model_selection import RandomizedSearchCV
randomized_search_cv=RandomizedSearchCV(svm.SVC(gamma='auto'),{
    'C':[1,5,10],
    'kernel':['rbf','linear']
},cv=5,n_iter=2,return_train_score=False)

In [88]:
randomized_search_cv.fit(X_train,y_train)


RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=2,
                   param_distributions={'C': [1, 5, 10],
                                        'kernel': ['rbf', 'linear']})

In [89]:
randomized_search_cv.cv_results_

{'mean_fit_time': array([0.00099778, 0.00079465]),
 'std_fit_time': array([1.59580236e-06, 3.97357105e-04]),
 'mean_score_time': array([0.00019937, 0.00079751]),
 'std_score_time': array([0.00039873, 0.00039876]),
 'param_kernel': masked_array(data=['linear', 'linear'],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'param_C': masked_array(data=[5, 10],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'params': [{'kernel': 'linear', 'C': 5}, {'kernel': 'linear', 'C': 10}],
 'split0_test_score': array([0.95238095, 0.9047619 ]),
 'split1_test_score': array([1., 1.]),
 'split2_test_score': array([1., 1.]),
 'split3_test_score': array([0.9047619, 0.9047619]),
 'split4_test_score': array([0.95238095, 0.95238095]),
 'mean_test_score': array([0.96190476, 0.95238095]),
 'std_test_score': array([0.03563483, 0.04259177]),
 'rank_test_score': array([1, 2])}

In [90]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.971429
1       1       linear         0.971429
2      10          rbf         0.961905
3      10       linear         0.952381
4      20          rbf         0.952381
5      20       linear         0.933333

In [91]:
randomized_search_cv.best_score_

0.9619047619047618

In [92]:
randomized_search_cv.best_params_

{'kernel': 'linear', 'C': 5}

In [97]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

model_params={
    'svm':{
        'model':svm.SVC(gamma='auto'),
        'param':{
            'C':[1,5,10],
            'kernel':['rbf','linear']
        }
    },
    'random_forest':{
        'model':RandomForestClassifier(),
        'param':{
            'n_estimators':[1,5,10]
        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'param': {
            'C': [1,5,10]
        }
    }
    
}

In [98]:
scores = []

for model_name, mp in model_params.items():
    clf =  GridSearchCV(mp['model'], mp['param'], cv=5, return_train_score=False)
    clf.fit(iris.data,iris.target)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.953333        {'n_estimators': 5}
2  logistic_regression    0.966667                   {'C': 5}

In [ ]:
from sklearn.model_selection import GridSearchCV
import pandas as pd
scores = []

for model_name, mp in model_params.items():
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(digits.data, digits.target)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df