In [7]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


In [9]:
df=pd.read_csv('spam.csv',encoding= 'unicode_escape')

In [10]:
df.head()

Category                                            Message  Unnamed: 2
0      ham  Go until jurong point, crazy.. Available only ...         NaN
1      ham                      Ok lar... Joking wif u oni...         NaN
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...         NaN
3      ham  U dun say so early hor... U c already then say...         NaN
4      ham  Nah I don't think he goes to usf, he lives aro...         NaN

In [11]:
df.drop('Unnamed: 2',axis='columns',inplace=True)

In [13]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    640  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [14]:
df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.Message,df.spam,test_size=0.3,random_state=0)


In [20]:
from sklearn.feature_extraction.text import CountVectorizer
countvectorizer=CountVectorizer()
X_train_count=countvectorizer.fit_transform(X_train)

In [21]:
X_train_count.toarray()[0:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [29]:
from sklearn.naive_bayes import MultinomialNB
multinomial_nb=MultinomialNB()
multinomial_nb.fit(X_train_count,y_train)



MultinomialNB()

In [30]:
X_test_count=countvectorizer.transform(X_test)
multinomial_nb.score(X_test_count,y_test)

0.979066985645933

In [31]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

In [33]:
emails_count=countvectorizer.transform(emails)

In [34]:
multinomial_nb.predict(emails_count)

array([0, 1], dtype=int64)

In [40]:
from sklearn.pipeline import Pipeline
mnnb_pipeline=Pipeline([
    ("countvectorizer",CountVectorizer()),
    ('multinomial_nb',MultinomialNB())
    
])

In [42]:
mnnb_pipeline.fit(X_train,y_train)

Pipeline(steps=[('countvectorizer', CountVectorizer()),
                ('multinomial_nb', MultinomialNB())])

In [43]:
mnnb_pipeline.score(X_test,y_test)

0.979066985645933

In [45]:
mnnb_pipeline.predict(emails)

array([0, 1], dtype=int64)